name: Analyze
description: Analyze next.js bundle size
inputs:
  workflow:
    required: true
    description: Workflow file name
runs:
  using: composite
  steps:
    - name: Analyze bundle
      run: npx -p nextjs-bundle-analysis report
      shell: bash
    - name: Upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: bundle
        path: .next/analyze/__bundle_analysis.json
    - name: Download base branch bundle stats
      continue-on-error: true
      id: download-base-stats
      uses: dawidd6/action-download-artifact@v7
      with:
        workflow: ${{ inputs.workflow }}
        branch: main
        name: bundle
        path: .next/analyze/base/bundle
    - name: Compare with base branch bundle
      if: ${{ steps.download-base-stats.outcome == 'success' }}
      run: ls -laR .next/analyze/base/bundle && npx -p nextjs-bundle-analysis compare
      shell: bash
    - name: Get comment body
      if: ${{ steps.download-base-stats.outcome == 'success' }}
      id: get-comment-body
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const fs = require('fs')
          const comment = fs.readFileSync('.next/analyze/__bundle_analysis_comment.txt', 'utf8')
          core.setOutput('body', comment)
    - name: Post bundle size comment to commit
      if: ${{ steps.download-base-stats.outcome == 'success' }}
      uses: peter-evans/commit-comment@v3
      with:
        body: ${{ steps.get-comment-body.outputs.body }}
