import { FC } from 'react';
import Head from 'next/head';
import { IndexPage } from '@c/pages/IndexPage';

export interface Props {}

// eslint-disable-next-line no-underscore-dangle
const _IndexPage: FC<Props> = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <IndexPage />
  </>
);

export default _IndexPage;
