import { FC } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { SchoolCard } from '@c/SchoolCard';
import { Hero } from '@c/Hero';

export interface Props {}

const IndexPage: FC<Props> = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <main>
      <Hero />
      <div className='py-8 sm:py-12 lg:py-16'>
        <div className='px-8 sm:px-12 lg:px-16 '>
          <h2 className='tracking-tight font-extrabold text-gray-900 text-2xl sm:text-4xl'>
            各学校について
          </h2>
        </div>
        <div className='flex lg:justify-around py-8 sm:py-12 lg:py-16 h-full overflow-scroll'>
          <Link href='/byu'>
            <a>
              <SchoolCard className='w-64 h-80 mx-8' colorClass='bg-byu'>
                <div className='relative h-full p-4'>
                  <Image
                    src='/byu.png'
                    alt='BYU Logo'
                    layout='fill'
                    objectFit='scale-down'
                  />
                </div>
              </SchoolCard>
            </a>
          </Link>
          <Link href='/byuh'>
            <a>
              <SchoolCard className='w-64 h-80 mx-8' colorClass='bg-byuh'>
                <div className='relative h-full p-4'>
                  <Image
                    src='/byuh.png'
                    alt='BYUH Logo'
                    layout='fill'
                    objectFit='scale-down'
                  />
                </div>
              </SchoolCard>
            </a>
          </Link>
          <Link href='/byui'>
            <a>
              <SchoolCard className='w-64 h-80 mx-8' colorClass='bg-byui'>
                <div className='relative h-full p-4'>
                  <Image
                    src='/byui.png'
                    alt='BYUI Logo'
                    layout='fill'
                    objectFit='scale-down'
                  />
                </div>
              </SchoolCard>
            </a>
          </Link>
        </div>
      </div>
    </main>
  </>
);

export default IndexPage;
